name: dockerized_django_stack

services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile.django
    container_name: dockerized_django_django
    user: "1000:1000"
    depends_on:
      - postgresdb
    volumes:
      - static_files:/project/staticfiles
      - media_files:/project/mediafiles
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: dockerized_django_nginx
    ports:
      - "8001:80"
    networks:
      - default
    volumes:
      - static_files:/static:ro
      - media_files:/media:ro
      - nginx_temp:/var/cache/nginx
      - nginx_run:/var/run/nginx
    depends_on:
      - django

volumes:
  static_files:
  media_files:
  nginx_temp:
  nginx_run: