name: dockerized_django_stack

services:
  postgresdb:
    image: postgres:17.2-alpine3.21
    container_name: dockerized_django_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  django:
    build:
      context: ./django
      dockerfile: Dockerfile.django
    container_name: dockerized_django_django
    user: "1000:1000"
    depends_on:
      - postgresdb
    volumes:
      - static_files:/project/staticfiles
      - media_files:/project/mediafiles
    env_file:
      - ./.env
    networks:
      - backend
      - frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: dockerized_django_nginx
    ports:
      - "8001:80"
    volumes:
      - static_files:/static:ro
      - media_files:/media:ro
      - nginx_temp:/var/cache/nginx
      - nginx_run:/var/run/nginx
    depends_on:
      - django
    networks:
      - frontend
      - npm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  postgres_data:
  static_files:
  media_files:
  nginx_temp:
  nginx_run:

networks:
  backend:
  frontend:
  npm-network:
    external: true
