name: project

services:
  postgresdb:
    image: postgres:17.2-alpine3.21
    container_name: project_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_django
    depends_on:
      - postgresdb
    volumes:
      - ./staticfiles:/project/staticfiles
      - ./mediafiles:/project/media
    env_file:
      - ./.env

  nginx:
    image: nginx:1.27.3-alpine-slim
    container_name: project_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/static:ro
      - ./mediafiles:/media:ro
    depends_on:
      - django

volumes:
  postgres_data:
